# Generated by Django 5.2.7 on 2025-12-03 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Credor'), (2, 'Investidor'), (3, 'Analista')], default=2),
        ),
    ]
