# Generated by Django 5.2.7 on 2025-12-04 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Precatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('valor_face', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tribunal', models.CharField(max_length=50)),
                ('status', models.SmallIntegerField(choices=[(1, 'Pendente'), (2, 'Disponivel'), (3, 'Vendido')], default=1)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precatorio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_oferta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Aguardando'), (2, 'Aceita'), (3, 'Recusada')], default=1)),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to=settings.AUTH_USER_MODEL)),
                ('precatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposta', to='ativos.precatorio')),
            ],
        ),
    ]
