# Generated by Django 6.0 on 2025-12-10 14:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Precatorio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("valor_face", models.DecimalField(decimal_places=2, max_digits=12)),
                ("valor_inicial", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tribunal", models.CharField(max_length=50)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "Pendente"), (2, "Disponivel"), (3, "Vendido")],
                        db_index=True,
                        default=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proposta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("valor_oferta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "Aguardando"), (2, "Aceita"), (3, "Recusada")],
                        db_index=True,
                        default=1,
                    ),
                ),
            ],
        ),
    ]
