# Generated by Django 6.0 on 2025-12-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ativos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precatorio",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "Pendente"), (2, "Disponivel"), (3, "Vendido")],
                db_index=True,
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "Aguardando"), (2, "Aceita"), (3, "Recusada")],
                db_index=True,
                default=1,
            ),
        ),
    ]
