# Generated by Django 6.0 on 2025-12-15 19:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ativos", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="precatorio",
            name="comissao",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10, verbose_name="Valor comissão"),
        ),
    ]
