# Generated by Django 6.0 on 2025-12-04 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ativos", "0002_alter_precatorio_status_alter_proposta_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="precatorio",
            name="dono",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="precatorios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="precatorio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="propostas",
                to="ativos.precatorio",
            ),
        ),
    ]
