# Generated by Django 6.0 on 2025-12-05 19:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ativos", "0003_alter_precatorio_dono_alter_proposta_precatorio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precatorio",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
